### ISSUE TITLE
`<img class="course-banner__image"` nemá atributy `width` a `height`, takže při načítání stránky poskakuje

### ISSUE THREAD

**Issue by FilipChalupa** [podlomar/kodim.cz#12]
![banner](https://user-images.githubusercontent.com/1045362/158910000-8999b07b-7b8a-45b0-a4e9-0bb5d3901a71.gif)

**Comment by FilipChalupa** [comment]
Proč je tohle zavřené? Nenašel jsem žádný commit, který by tenhle problém řešil a stránka https://stage.kodim.cz/kurzy/daweb stále poskakuje.

**Comment by podlomar** [comment]
Já jsem myslel, že jsi to udělal v tom předchozím PRku.

**Comment by FilipChalupa** [comment]
To jsem udělal na frontpage, protože obrázek je ve stejném repu `kodim.cz`. Tady jde ale o obrázek kurzu, který má svg v jiném repu a tím pádem nevím jeho rozměry.

**Comment by podlomar** [comment]
Ahaaa, tak to jsem si spletl.

**Comment by FilipChalupa** [comment]
No, mohl sem dát jasněji vědět, že je to podobný problém, ale jiný. Pardon. :D
