### ISSUE TITLE
Podbarvení <code> elementů

### ISSUE THREAD

**Issue by FilipJirsak** [podlomar/kodim.cz#15]
Bylo by dobré podbarvit elementy `<code>`, podobně jako to dělá třeba Slack nebo GitHub, aby bylo zřetelnější, kde začínají a končí. Např. pokud se `<code>` objeví na konci věty a je za ním tečka, stává se, že účastnice tečku opíší do kódu – Viz třeba `Math.PI` zde https://stage.kodim.cz/kurzy/daweb/zaklady-js/knihovny-vlastni-funkce/cv-vlastni-funkce#cvlekce%3Eobsah-elipsy

**Comment by FilipChalupa** [comment]
Loni jsem řešil podobný problém zde: https://czechitas-podklady-web.github.io/HTML-a-CSS-2/nunjucks-podminky/

Osvědčilo se mi lehce šedé pozadí. Viz CSS v devtools.

**Comment by FilipChalupa** [comment]
Už vyřešeno a nasazeno.

<img width="267" alt="image" src="https://user-images.githubusercontent.com/1045362/161452723-d9440290-1ed7-4437-a7c1-f784cecade6a.png">

**Comment by FilipChalupa** [comment]
@podlomar, můžeš issue prosím zavřít?

**Comment by FilipChalupa** [comment]
Koukám, že může zavírat i autor issue. Cc. @FilipJirsak
