### ISSUE TITLE
Chybí syntax highlighting u bloků ```js/html/css

### ISSUE THREAD

**Issue by FilipChalupa** [podlomar/kodim.cz#17]
Kód je tak pro návštěvníky hůře čitelný jako například zde:

![](https://user-images.githubusercontent.com/1045362/160948835-df17240c-9de4-4599-a54c-e72ae99f3183.png)

vs staré kodim

![](https://user-images.githubusercontent.com/1045362/160948886-a510af2f-cf30-40a2-99e6-8f18972d3265.png)

**Comment by FilipJirsak** [comment]
Tohle už je vyřešené, ne?

**Comment by FilipChalupa** [comment]
Ano. Vyřešené.
