### ISSUE TITLE
Část nadpisu která je v `<code>` chybí v postranním menu

### ISSUE THREAD

**Issue by lutydlitatova** [podlomar/kodim.cz#34]
Nadpis kapitoly co obsahuje styl `<code>` se nesprávně zobrazí v menu. Chybí celá `<code>` část.

![image (2)](https://user-images.githubusercontent.com/28315126/176538075-60a77d7d-4162-48e7-b88b-b5aa6c476c8d.png)

cc @pavelsuk

**Comment by pavelsuk** [comment]
Priklad stranky, kde je to videt: https://stage.kodim.cz/kurzy/uvod-do-progr-2/uvod-do-programovani-2/tridy/str

**Comment by podlomar** [comment]
Opraveno ve verzi 1.5.10
