### ISSUE TITLE
inviteToken skupiny je "skoro" povinný

### ISSUE THREAD

**Issue by FilipJirsak** [podlomar/kodim.cz#56]
`inviteToken` je ve schématu `Group` označený jako nepovinný. Ale unikátní index v MongoDB povoluje jenom jednu skupinu bez `inviteToken`, další považuje za duplicitu. Pokud jde index v MongoDB nastavit tak, že prázdné hodnoty ignoruje, chtělo by to index nad `Group.inviteToken` takto nastavit.

**Comment by FilipChalupa** [comment]
Co ho udělat rovnou úplně povinný? Jestli ve starých datech chybí, tak něčím doplnit a do budoucna tak strukturu dat zjednodušit.

**Comment by podlomar** [comment]
Tohle už je ve verzi 2.x jinak a lépe
