### ISSUE TITLE
U citací je posuvník

### ISSUE THREAD

**Issue by FilipJirsak** [podlomar/kodim.cz#66]
Citace (`<blockquote>`) jsou špatně nastylované, nevejdou se vertikálně do zobrazeného boxu a vertikálně mírně skrolují (alespoň an některých rozlišeních).

**Comment by FilipChalupa** [comment]
![image](https://user-images.githubusercontent.com/1045362/232309478-770ed182-ef9c-4484-9cb0-3e77d47c3b45.png)
