### ISSUE TITLE
Jedny materiály – více kurzů

### ISSUE THREAD

**Issue by FilipJirsak** [podlomar/kodim.cz#67]
Připadá mi zvláštní, když účastnice dílčích kurzů (např. JavaScript 2) odkazujeme na kus materiálů z Digitální akademie. A chápu, že je to matoucí i pro lektory (kteří by ale o práci s materiály měli vědět dost na to, aby tomu rozuměli) i kouče (pro které by v zásadě informace „jdu koučovat na kurz JS2, najdu si na kódim.cz kurz JS2“ měla být dostatečná).
Líbilo by se mi, kdyby bylo možné ty samé materiály zobrazovat pod různými kurzy – resp. zobrazit pod tím kurzem jen část materiálů, které odpovídají danému kurzu.
A pak by možná dávalo smysl i nějaké podmíněné zobrazení typu „tohle zobrazovat jen v akademii“.

**Comment by podlomar** [comment]
Hotovo, už je to možné a funguje to pro JS 1 i React 1.
