### ISSUE TITLE
Sjednotit `/api/me` s `/api/admin/groups/*`, aby obsahovaly stejný unikátní identifikátor

### ISSUE THREAD

**Issue by FilipChalupa** [podlomar/kodim.cz#71]
Zatím je celkem komplikované například udělat samostatnou aplikaci s ověřením přes `/api/me` pro konkrétní skupinu uživatelů, protože nelze ověřit na základě dat z `/api/me`, jestli uživatel do nějaké skupiny patří.

#### Ukázka dat z `/api/me`

```json
{
    "name": "Filip Chalupa",
    "email": "chalupa.filip@gmail.com",
    "avatarUrl": "https://avatars.githubusercontent.com/u/1045362?v=4"
}
```

#### Částečná ukázka dat z `/api/admin/groups/*`

```json
{
    "url": "https://kodim.cz/api/admin/users/FilipChalupa",
    "login": "FilipChalupa",
    "name": "Filip Chalupa"
}
```

Jediná společná vlastnost je `name` a ta určitě není unikátní. Co přidat do obou endpointů `id` nebo do `/api/me` přidat `login`?

**Comment by podlomar** [comment]
Tyto endpointy už verzi 2.x nejsou a nebudou
