### ISSUE TITLE
Odkazy na repozitáře ve cvičeních otevírat v novém tabu

### ISSUE THREAD

**Issue by kareltilcer** [podlomar/kodim.cz#81]
Bylo by fajn otevírat odkazy na repozitáře ze cvičení v novém okně/tabu. Člověk málokdy chce repozitář otevřít v tom stejném, protože většinou bude chtít následně koukat do zadání toho cvičení.

**Comment by FilipChalupa** [comment]
> Člověk málokdy chce repozitář otevřít v tom stejném

Co když ale nechce?

**Comment by podlomar** [comment]
Po diskuzí to vypadá, že bude lepší naučit účastnice, jak ovládat prohlížeč.
