### ISSUE TITLE
Chybné zobrazení obsahu lekce

### ISSUE THREAD

**Issue by FilipJirsak** [podlomar/kodim.cz#84]
V lekci [JavaScript1.10 – Cykly](https://kodim.cz/vyvoj-webu/daweb/js1/cykly/uvod) se zobrazují následující názvy kapitol:
* Pole a nodelist-a-foreach.md
* Cykly s map.md
Navíc jsou ty názvy rozdělené do dvou řádků.

Asi nějaká chyba se speciálními znaky.

**Comment by podlomar** [comment]
Duplikace #80
