### ISSUE TITLE
Scrollbary u výpisu kódu

### ISSUE THREAD

**Issue by FilipJirsak** [podlomar/kodim.cz#88]
Poměrně často se stává, že výpis kódu má horizontální scrollbar, což je otravné a ošklivé.

1. V některých případech je zbytečný, je zobrazen veškerý kód a scrollbar je jen kvůli okrajům (např. [Document Object Model](https://kodim.cz/vyvoj-webu/daweb/js1/dom-innerhtml/dom#:~:text=p%C5%99%C3%ADmo%20obsah%20str%C3%A1nky.-,Document%20Object%20Model,-K%20pr%C3%A1ci%20s), [Knihovny – Kontrola vstupu](https://kodim.cz/vyvoj-webu/daweb/js1/knihovny-vlastni-funkce/knihovny#:~:text=a%20m%C3%A1te%20vystar%C3%A1no.-,Kontrola%20vstupu,-Jeden%20z%20velmi), [Kontrola DIČ – druhé řešení](https://kodim.cz/vyvoj-webu/daweb/js1/knihovny-vlastni-funkce/cv-vlastni-funkce/kontrola-dic#:~:text=CZA12345678-,%C5%98e%C5%A1en%C3%AD,-Skr%C3%BDt)).
1. Někdy je kód jen o trochu širší a asi by pomohlo dát mu trochu víc prostoru, ať ho nemusíme zbytečně zalamovat (např. [Formátování data](https://kodim.cz/vyvoj-webu/daweb/js1/knihovny-vlastni-funkce/ulozky-na-doma/formatovani-data).
1. Někdy je kód výrazně širší a bude potřeba ho zalomit – to by měl v ideálním případě hlídat Prettier v materiálech (např. poslední kód v [Vlastnost innerHTML](https://kodim.cz/vyvoj-webu/daweb/js1/dom-innerhtml/innerhtml) nebo [Obory platnosti a funkce](https://kodim.cz/vyvoj-webu/daweb/js1/funkce-obory/zastinovani#:~:text=Obory%20platnosti%20a%20funkce)).

Nemám pro to přímo řešení, ale prvním dvěma bodům by mohlo pomoci, pokud by se obsah kódu roztáhnul (skoro) na šířku plochy, kterou zabírá. Tj. text kódu by byl širší, než samotný text lekce – to ale podle mne ničemu nevadí, protože už to šedé pozadí dělá kód opticky širším. Zároveň by bylo dobré, aby byl stejně široký i kód v seznamech (číslovaných či odrážkových – např. [zde](https://kodim.cz/vyvoj-webu/daweb/js1/dom-innerhtml/dom-elementy#:~:text=V%C5%A1imn%C4%9Bte%20si%20hned%20dvou%20d%C5%AFle%C5%BEit%C3%BDch%20v%C4%9Bc%C3%AD)) – abychom při zalamování kódu nemuseli neustále hlídat, zda jsme uvnitř seznamu nebo mimo (a Prettier by to asi neuměl zkontrolovat).

**Comment by FilipChalupa** [comment]
Je určitě současný stav problém? Respektive má to lepší řešení?

- Pokud se ubere boční padding, tak kód nebude zarovnaný s ostatním textem.
- Pokud se zruší scrollbar tam, kde kód se sice vejde, ale padding ne, bude to podle mne vypadat divně (na jedné straně jiný padding než na druhé) a ještě to nejde v CSS napsat.
- Pokud vynutíme v Prettieru užší řádky, stejně to nevyřeší užší displaye/zobrazení a bude to víc „rozbíjet“ kód.
- Zalamování řádků na dva a více, které jsou ve skutečnosti ve zdroji jeden, se, hádám, že pro začátečníka, blbě čte, protože je to trochu kouzelné. (I za předpokladu, že by se k výpisu kódu přidaly čísla řádků.)

**Comment by FilipJirsak** [comment]
Vadí to, když text kódu nebude zarovnaný s ostatním textem? Stejně teď opticky zarovnaný není, protože to tmavé pozadí je výrazné a přesahuje mimo text.

> Pokud se zruší scrollbar tam, kde kód se sice vejde, ale padding ne, bude to podle mne vypadat divně (na jedné straně jiný padding než na druhé) a ještě to nejde v CSS napsat.
Tohle bych nedělal. Za mne by bylo ideální mít všechny úryvky kódu stejně široké (tedy bez ohledu na to, zda jsou v seznamu nebo mimo něj), a získat pro kód větší prostor, než má teď. A pak na tento širší prostor nastavit Prettier, aby kód musel správně naformátovat jeho autor.

**Comment by FilipChalupa** [comment]
Možná jsem tě nepochopil, ale myslíš něco takového?

### Teď:

![image](https://github.com/podlomar/kodim.cz/assets/1045362/cedc9229-dc52-48e2-877b-6f0f5002eb11)

### Návrh:

![image](https://github.com/podlomar/kodim.cz/assets/1045362/6161f47b-bd46-495f-8395-f9d768f5bb14)

**Comment by FilipChalupa** [comment]
> Stejně teď opticky zarovnaný není, protože to tmavé pozadí je výrazné a přesahuje mimo text.

Mně současný stav zarovnaný přijde i přes to tmavé pozadí. 🤷‍♀️

**Comment by FilipJirsak** [comment]
> Možná jsem tě nepochopil, ale myslíš něco takového?

Ano, něco takového. Případně by ten blok kódu mohl přesahovat sloupec s obsahem i doprava, aby to bylo symetrické.

Nemám v rukávu nějaké řešení, jak to udělat, aby to vypadalo lépe. Ale kdyby se na nějaké řešení přišlo, byl bych rád :-)

**Comment by FilipChalupa** [comment]
> Případně by ten blok kódu mohl přesahovat sloupec s obsahem i doprava, aby to bylo symetrické

Jasný. Ten padding jsem upravil nalevo i napravo. Jen to není vidět, protože se kód většinou netrefí přesnou délkou.

**Comment by FilipChalupa** [comment]
Jinak mně teda současný stav přijde dobrý. Nebo teda nedokáži si představit, jak by to mohlo být lepší. 🤷‍♀️

Někde už jsme se asi i bavili o číslech řádků, ale to je tak asi všechno.

**Comment by podlomar** [comment]
Já si taky nedokážu představit lepší řešení, takže prozatím zavírám, ať v tom mám porádek.
