### ISSUE TITLE
Error 404 chybně hlásí http status kód 200 (Forbidden podobně)

### ISSUE THREAD

**Issue by FilipChalupa** [podlomar/kodim.cz#9]
Nenašel jsem řešení pro react-router v6, protože má nedotaženou dokumentaci, tak od toho pro zatím dávám ruce pryč. Ve v5 je to hezky popsané přes kontext, což ale v šestce nefunguje.

v6, kde jen zmiňují, že status code by se měl řešit: https://reactrouter.com/docs/en/v6/guides/ssr

v5, kde popisují context: https://v5.reactrouter.com/web/guides/server-rendering

**Comment by podlomar** [comment]
Tohle už řeší Next.js automaticky
